version: "3.9"
services:
  docker_realtime:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: realtime_docker
    tty: true
    privileged: true
    network_mode: host
    volumes:
      - ../src:/benchmark/src
      - ../test:/benchmark/test
