name: Tests

on:
  push:
    paths:
      - 'docker/Dockerfile'
      - 'docker/docker-compose.yml'
      - 'src/**'
      - 'test/**'
  schedule:
    - cron: "0 12 1 * *"

jobs:
  docker-compose-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Launch the Docker
        run: docker-compose -f docker/docker-compose.yml up --detach
      - name: Run BATS Bash unit-tests
        run: |
          docker exec realtime_docker bash -c '
            cd test && 
            for TEST_FILE in $(find . -maxdepth 1 -name "*.bats"); do 
              ./"${TEST_FILE}";
            done
          '
      - name: Stop Docker
        run: docker stop realtime_docker

